In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns  
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

# Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

Revisiting our dataframe

In [4]:
df = pd.read_csv("bmi.csv")
sex = pd.get_dummies(df["Gender"], drop_first=True)
new_df  = pd.concat([df,sex], axis=1)
new_df.drop("Gender", inplace=True, axis = 1)

In [5]:
X = new_df.drop("Index", axis=1)
y = new_df["Index"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [6]:
tree = DecisionTreeClassifier()

In [7]:
tree.fit(X_train, y_train)
tree_pred = tree.predict(X_test)

In [8]:
print(classification_report(y_test,tree_pred))
print(confusion_matrix(y_test,tree_pred))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.71      0.83      0.77         6
           2       0.87      0.87      0.87        23
           3       0.75      0.63      0.69        19
           4       0.74      0.68      0.71        38
           5       0.88      0.94      0.91        63

    accuracy                           0.82       150
   macro avg       0.74      0.83      0.77       150
weighted avg       0.82      0.82      0.82       150

[[ 1  0  0  0  0  0]
 [ 1  5  0  0  0  0]
 [ 0  2 20  1  0  0]
 [ 0  0  2 12  5  0]
 [ 0  0  1  3 26  8]
 [ 0  0  0  0  4 59]]


Let's see how well our model will perform with Random Forest Classifier

# Random Forest Classifier

In [10]:
rfc = RandomForestClassifier()

In [11]:
rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)

In [12]:
print(classification_report(y_test,rfc_pred))
print("\n")
print(confusion_matrix(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.71      0.83      0.77         6
           2       0.91      0.91      0.91        23
           3       0.80      0.63      0.71        19
           4       0.79      0.82      0.81        38
           5       0.92      0.97      0.95        63

    accuracy                           0.87       150
   macro avg       0.69      0.69      0.69       150
weighted avg       0.86      0.87      0.86       150



[[ 0  1  0  0  0  0]
 [ 0  5  1  0  0  0]
 [ 0  1 21  1  0  0]
 [ 0  0  1 12  6  0]
 [ 0  0  0  2 31  5]
 [ 0  0  0  0  2 61]]


C:\Users\hottec\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hottec\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\hottec\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
